####################################################################################################
#                                                                                                  #
#                                   DO NOT COMMIT LOCAL (TEST) CHANGES                             #
#                                                                                                  #
####################################################################################################

#+++++++++++++++++++++++++++++++ UNDERLYING RDBMS ENGINE PROPERTIES +++++++++++++++++++++++++++++++#
# Database engine
# Valid options: POSTGRESQL, DB2, MYSQL
# Database engine => port: MYSQL => 3306, POSTGRESQL =>5432, DB2 => 50000
database.engine = MYSQL
# Database host
database.host = localhost
# Database port
database.port = 3306
# Database user
database.user = user
# Database password 
database.password = password
# Database lubm70MDL
database.name = lubm100MDL
# Database ontology
# database.ontology = ressources/LUBM-ex-20.owl
# Database ontology DLP  dblp-ontology.dlp npd-v2-ql.dlp
database.ontologyDlp = ressources/npd-v2-ql.dlp
# OWL files 
# owl.filesDirectory = /local/data/LUBM/Base_1MT/
# Output of dlp conversion /local/data/npd-scale1/npd1.nt /local/data/DBLP/dblp.nt  /local/data/DLP/Base_1MT/
# /local/data/npd-scalex/abox50/npd50.nt 
dlp.filesDirectory = /local/data/npd-scale1/npd1.nt
# dlp jar file
# dlp.jarfile = loadDL/lib/owl2dlgp-1.1.0.jar
# database.dump1 = dump1.dump
# database.dump2 = dump2.dump
# database.dump3 = dump3.dump
# Max chuck for DB2
database.maxChunk = 100

database.load = true

